/**
 * Prisma Enums - Auto-generated from Prisma schema
 *
 * DO NOT EDIT THIS FILE MANUALLY!
 *
 * This file is auto-generated by scripts/generate-prisma-enums.js
 * Run `pnpm generate:enums` to regenerate.
 *
 * @generated
 */

import { z } from 'zod';

/** ============================================================================ */
export const SexTypeSchema = z.enum(['UNKNOWN', 'MALE', 'FEMALE']);
export type SexType = z.infer<typeof SexTypeSchema>;

/** File metadata itself remains owned by SSO and is not stored here. */
export const FileBucketVendorSchema = z.enum(['oss', 'us3', 'qiniu', 's3', 'gcs', 'tos', 'tencent', 'ksyun']);
export type FileBucketVendor = z.infer<typeof FileBucketVendorSchema>;

export const FileEnvTypeSchema = z.enum(['dev', 'test', 'prod', 'produs', 'prodap']);
export type FileEnvType = z.infer<typeof FileEnvTypeSchema>;

export const AuditActionTypeSchema = z.enum(['CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'ACCESS', 'EXPORT', 'IMPORT']);
export type AuditActionType = z.infer<typeof AuditActionTypeSchema>;

export const KnowledgeSpaceKindSchema = z.enum(['PERSONAL', 'TEAM', 'ENTERPRISE']);
export type KnowledgeSpaceKind = z.infer<typeof KnowledgeSpaceKindSchema>;

export const KnowledgeSpaceMemberRoleSchema = z.enum(['OWNER', 'ADMIN', 'EDITOR', 'VIEWER']);
export type KnowledgeSpaceMemberRole = z.infer<typeof KnowledgeSpaceMemberRoleSchema>;

export const KnowledgeSourceTypeSchema = z.enum(['UPLOAD', 'EDITOR', 'LOCAL_FILE', 'FEISHU', 'WECOM', 'WECOM_EXPORT', 'SESSION', 'FILE_LINK']);
export type KnowledgeSourceType = z.infer<typeof KnowledgeSourceTypeSchema>;

export const KnowledgeSourceStatusSchema = z.enum(['DRAFT', 'ACTIVE', 'SYNCING', 'DEGRADED', 'DISABLED']);
export type KnowledgeSourceStatus = z.infer<typeof KnowledgeSourceStatusSchema>;

export const DocumentStatusSchema = z.enum(['DISCOVERED', 'PROCESSING', 'READY', 'FAILED', 'BLOCKED', 'DELETED']);
export type DocumentStatus = z.infer<typeof DocumentStatusSchema>;

export const RevisionStatusSchema = z.enum(['PENDING', 'PARSED', 'SEARCH_READY', 'READY', 'FAILED', 'DELETED']);
export type RevisionStatus = z.infer<typeof RevisionStatusSchema>;

export const MemoryTypeSchema = z.enum(['WORKING', 'EPISODIC', 'SEMANTIC', 'PROCEDURAL']);
export type MemoryType = z.infer<typeof MemoryTypeSchema>;

export const MemoryStatusSchema = z.enum(['CANDIDATE', 'CONFIRMED', 'SUPERSEDED', 'FORGOTTEN', 'EXPIRED']);
export type MemoryStatus = z.infer<typeof MemoryStatusSchema>;

export const MemoryScopeSchema = z.enum(['SESSION', 'USER', 'TEAM', 'ENTERPRISE']);
export type MemoryScope = z.infer<typeof MemoryScopeSchema>;

export const MemoryStrategyStatusSchema = z.enum(['CANDIDATE', 'TRIAL', 'ACTIVE', 'RETIRED']);
export type MemoryStrategyStatus = z.infer<typeof MemoryStrategyStatusSchema>;

export const MemoryStrategyTrialOutcomeSchema = z.enum(['PASS', 'FAIL']);
export type MemoryStrategyTrialOutcome = z.infer<typeof MemoryStrategyTrialOutcomeSchema>;

export const MemoryStrategyReplayTaskStatusSchema = z.enum(['QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'DEAD_LETTER']);
export type MemoryStrategyReplayTaskStatus = z.infer<typeof MemoryStrategyReplayTaskStatusSchema>;

export const MemoryStrategyReplayPlanStatusSchema = z.enum(['DRAFT', 'PUBLISHED', 'RETIRED']);
export type MemoryStrategyReplayPlanStatus = z.infer<typeof MemoryStrategyReplayPlanStatusSchema>;

export const MemoryStrategyBaselineStatusSchema = z.enum(['NOT_REQUESTED', 'QUEUED', 'RUNNING', 'COMPLETED', 'FAILED']);
export type MemoryStrategyBaselineStatus = z.infer<typeof MemoryStrategyBaselineStatusSchema>;

export const DocumentPrincipalTypeSchema = z.enum(['USER', 'GROUP', 'TENANT']);
export type DocumentPrincipalType = z.infer<typeof DocumentPrincipalTypeSchema>;

export const EnvironmentFactStatusSchema = z.enum(['ACTIVE', 'SUPERSEDED', 'EXPIRED', 'REVOKED']);
export type EnvironmentFactStatus = z.infer<typeof EnvironmentFactStatusSchema>;

export const MemorySkillStatusSchema = z.enum(['CANDIDATE', 'TRIAL', 'ACTIVE', 'STALE', 'RETIRED']);
export type MemorySkillStatus = z.infer<typeof MemorySkillStatusSchema>;

export const DocumentPrincipalPermissionSchema = z.enum(['READ', 'EDIT']);
export type DocumentPrincipalPermission = z.infer<typeof DocumentPrincipalPermissionSchema>;

/** subjectUserId，不形成独立 ACL principal。 */
export const KnowledgePrincipalTypeSchema = z.enum(['USER', 'GROUP', 'TEAM', 'SERVICE', 'AGENT_RUNTIME']);
export type KnowledgePrincipalType = z.infer<typeof KnowledgePrincipalTypeSchema>;

export const KnowledgePrincipalSourceSchema = z.enum(['SSO', 'MODELS', 'AGENTS', 'KNOWLEDGE']);
export type KnowledgePrincipalSource = z.infer<typeof KnowledgePrincipalSourceSchema>;

export const KnowledgePrincipalStatusSchema = z.enum(['ACTIVE', 'SUSPENDED', 'REVOKED']);
export type KnowledgePrincipalStatus = z.infer<typeof KnowledgePrincipalStatusSchema>;

/** API Key 绑定状态（KnowledgeApiKeyBinding 是 credential，不是 Principal）。 */
export const KnowledgeApiKeyStatusSchema = z.enum(['ACTIVE', 'SUSPENDED', 'REVOKED']);
export type KnowledgeApiKeyStatus = z.infer<typeof KnowledgeApiKeyStatusSchema>;

/** 触发底层状态变更；过期由 cron worker 标记为 EXPIRED。 */
export const KnowledgePolicyApprovalStatusSchema = z.enum(['PENDING', 'APPROVED', 'REJECTED', 'EXPIRED']);
export type KnowledgePolicyApprovalStatus = z.infer<typeof KnowledgePolicyApprovalStatusSchema>;

/** AclGrant 资源类型；resourceId 为多态 UUID 字符串，不强制 FK。 */
export const KnowledgeAclResourceTypeSchema = z.enum(['DOCUMENT', 'MEMORY', 'KNOWLEDGE_REVISION', 'KNOWLEDGE_SPACE']);
export type KnowledgeAclResourceType = z.infer<typeof KnowledgeAclResourceTypeSchema>;

/** AclGrant 权限语义（docs/0901/03 §5）。 */
export const KnowledgeAclPermissionSchema = z.enum(['DISCOVER', 'READ', 'USE', 'CONTRIBUTE', 'CONFIRM', 'ADMIN', 'EXPORT']);
export type KnowledgeAclPermission = z.infer<typeof KnowledgeAclPermissionSchema>;

export const IngestionStatusSchema = z.enum(['QUEUED', 'FETCHING', 'PARSING', 'CHUNKING', 'EMBEDDING', 'INDEXING', 'COMPLETED', 'FAILED', 'CANCELLED']);
export type IngestionStatus = z.infer<typeof IngestionStatusSchema>;

export const IntegrationObjectScanStatusSchema = z.enum(['SKIPPED', 'PASSED', 'FLAGGED']);
export type IntegrationObjectScanStatus = z.infer<typeof IntegrationObjectScanStatusSchema>;

export const ProjectionKindSchema = z.enum(['OBJECT', 'VECTOR', 'GRAPH']);
export type ProjectionKind = z.infer<typeof ProjectionKindSchema>;

export const ProjectionStatusSchema = z.enum(['PENDING', 'READY', 'STALE', 'DELETING', 'FAILED']);
export type ProjectionStatus = z.infer<typeof ProjectionStatusSchema>;

export const RecallEndpointSchema = z.enum(['SEARCH', 'MEMORY_RECALL', 'CONTINUATION']);
export type RecallEndpoint = z.infer<typeof RecallEndpointSchema>;

export const HandoffStateSchema = z.enum(['OPEN', 'ACCEPTED', 'CANCELLED', 'EXPIRED']);
export type HandoffState = z.infer<typeof HandoffStateSchema>;

export const MemoryFeedbackKindSchema = z.enum(['HELPFUL', 'NOT_HELPFUL', 'STALE', 'WRONG', 'USER_CORRECTION']);
export type MemoryFeedbackKind = z.infer<typeof MemoryFeedbackKindSchema>;

export const MemoryConflictSeveritySchema = z.enum(['LOW', 'MEDIUM', 'HIGH', 'CRITICAL']);
export type MemoryConflictSeverity = z.infer<typeof MemoryConflictSeveritySchema>;

export const MemoryExtractionDecisionSchema = z.enum(['store', 'update', 'merge', 'skip']);
export type MemoryExtractionDecision = z.infer<typeof MemoryExtractionDecisionSchema>;

export const MemoryExtractionConflictReasonSchema = z.enum(['CONTRADICTS_CONFIRMED', 'COMPETING_CANDIDATES']);
export type MemoryExtractionConflictReason = z.infer<typeof MemoryExtractionConflictReasonSchema>;

export const MemoryConflictStateSchema = z.enum(['OPEN', 'INVESTIGATING', 'RESOLVED', 'DISMISSED']);
export type MemoryConflictState = z.infer<typeof MemoryConflictStateSchema>;

export const MemoryConflictResolutionTypeSchema = z.enum(['SUPERSEDE', 'RETIRE', 'ADD_EVIDENCE', 'DISMISS']);
export type MemoryConflictResolutionType = z.infer<typeof MemoryConflictResolutionTypeSchema>;

export const CapabilityKindSchema = z.enum(['MODEL', 'TOOL', 'DATA_SOURCE', 'POLICY']);
export type CapabilityKind = z.infer<typeof CapabilityKindSchema>;

export const CapabilityTrustClassSchema = z.enum(['COMMUNITY', 'VERIFIED', 'ENTERPRISE']);
export type CapabilityTrustClass = z.infer<typeof CapabilityTrustClassSchema>;

export const CapabilityGapStatusSchema = z.enum(['OPEN', 'PROPOSED', 'TRIAL', 'RESOLVED', 'DISMISSED']);
export type CapabilityGapStatus = z.infer<typeof CapabilityGapStatusSchema>;

export const CapabilitySensitivityClassSchema = z.enum(['LOW', 'MEDIUM', 'HIGH', 'CRITICAL']);
export type CapabilitySensitivityClass = z.infer<typeof CapabilitySensitivityClassSchema>;

export const CapabilityProposalStatusSchema = z.enum(['DRAFT', 'SUBMITTED', 'NEEDS_INFO', 'REJECTED', 'APPROVED_FOR_TRIAL', 'TRIAL_RUNNING', 'TRIAL_SUCCEEDED', 'TRIAL_FAILED', 'EXPIRED', 'REVOKED']);
export type CapabilityProposalStatus = z.infer<typeof CapabilityProposalStatusSchema>;

export const CapabilityApprovalDecisionSchema = z.enum(['REQUEST_INFO', 'APPROVE_TRIAL', 'REJECT', 'REVOKE']);
export type CapabilityApprovalDecision = z.infer<typeof CapabilityApprovalDecisionSchema>;

export const CapabilityProposalOriginSchema = z.enum(['GAP', 'DIRECT', 'IMPORT']);
export type CapabilityProposalOrigin = z.infer<typeof CapabilityProposalOriginSchema>;

export const CapabilityBindingStatusSchema = z.enum(['REQUESTED', 'BINDING', 'READY', 'FAILED', 'REVOKING', 'REVOKED']);
export type CapabilityBindingStatus = z.infer<typeof CapabilityBindingStatusSchema>;

export const CapabilityTrialOutcomeClassSchema = z.enum(['PASS', 'PARTIAL', 'FAIL', 'VIOLATION']);
export type CapabilityTrialOutcomeClass = z.infer<typeof CapabilityTrialOutcomeClassSchema>;

export const UsageRuleStatusSchema = z.enum(['CANDIDATE', 'TRIAL', 'ACTIVE', 'STALE', 'RETIRED']);
export type UsageRuleStatus = z.infer<typeof UsageRuleStatusSchema>;

/** @repo/contracts 保持一一对应；新增值需先扩 Zod schema，再扩 Prisma enum。 */
export const EntityStatusSchema = z.enum(['EXTRACTED', 'VALIDATED', 'CANDIDATE', 'CANONICAL', 'CONFLICTED', 'REJECTED', 'SUPERSEDED', 'MERGED']);
export type EntityStatus = z.infer<typeof EntityStatusSchema>;

export const RelationStatusSchema = z.enum(['EXTRACTED', 'VALIDATED', 'CANDIDATE', 'CONFIRMED', 'CONFLICTED', 'SUPERSEDED', 'REJECTED']);
export type RelationStatus = z.infer<typeof RelationStatusSchema>;

/** PROPOSED → ACCEPTED / REJECTED；ACCEPTED → REVERSED（可撤销，投影可重建）。 */
export const EntityMergeStatusSchema = z.enum(['PROPOSED', 'ACCEPTED', 'REJECTED', 'REVERSED']);
export type EntityMergeStatus = z.infer<typeof EntityMergeStatusSchema>;

/** Zod schema，再扩 Prisma enum。 */
export const ProvenanceEntityTypeSchema = z.enum(['DOCUMENT_REVISION', 'CHUNK', 'MEMORY', 'ENTITY_ASSERTION', 'RELATION_ASSERTION', 'PROJECTION_PAYLOAD', 'DECISION_RECORD', 'RECALL_TRACE']);
export type ProvenanceEntityType = z.infer<typeof ProvenanceEntityTypeSchema>;

export const ProvenanceActivityTypeSchema = z.enum(['SOURCE_SYNC', 'PARSE', 'NORMALIZE', 'SPLIT', 'EMBED', 'EXTRACT_ENTITY', 'EXTRACT_RELATION', 'RESOLVE_CONFLICT', 'MERGE_ENTITY', 'PROJECTION_QDRANT', 'PROJECTION_NEO4J', 'PROJECTION_MINIO', 'MEMORY_CONFIRM', 'MEMORY_FORGET', 'MEMORY_SUPERSEDE', 'RECALL_EXECUTE', 'DECISION_RECORD', 'POLICY_EVALUATION']);
export type ProvenanceActivityType = z.infer<typeof ProvenanceActivityTypeSchema>;

export const ProvenanceActorTypeSchema = z.enum(['USER', 'AGENT', 'WORKER', 'SYSTEM', 'INTEGRATION']);
export type ProvenanceActorType = z.infer<typeof ProvenanceActorTypeSchema>;

/** Prisma enum 值不允许连字符；由契约层 PipelineStepKindSchema 强制闭集。 */
export const KnowledgePipelineRunStatusSchema = z.enum(['PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'DEAD_LETTER']);
export type KnowledgePipelineRunStatus = z.infer<typeof KnowledgePipelineRunStatusSchema>;

export const KnowledgePipelineStepStatusSchema = z.enum(['PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'DEAD_LETTER', 'SKIPPED']);
export type KnowledgePipelineStepStatus = z.infer<typeof KnowledgePipelineStepStatusSchema>;

/** 状态机：CANDIDATE → CONFIRMED → SUPERSEDED | REJECTED；outcome 是闭集。 */
export const KnowledgeDecisionOutcomeSchema = z.enum(['ALLOW', 'DENY', 'DEFER', 'OVERRIDE', 'UNKNOWN']);
export type KnowledgeDecisionOutcome = z.infer<typeof KnowledgeDecisionOutcomeSchema>;

export const KnowledgeDecisionStatusSchema = z.enum(['CANDIDATE', 'CONFIRMED', 'SUPERSEDED', 'REJECTED']);
export type KnowledgeDecisionStatus = z.infer<typeof KnowledgeDecisionStatusSchema>;

/** TenantOntologyVersionSchema.status 闭集一一对应。 */
export const KnowledgeOntologyStatusSchema = z.enum(['DRAFT', 'WARNING', 'ENFORCE', 'RETIRED']);
export type KnowledgeOntologyStatus = z.infer<typeof KnowledgeOntologyStatusSchema>;

/** 本体约束严重级别；ENFORCE 语义只在 ontology status=ENFORCE 时生效。 */
export const KnowledgeOntologyConstraintSeveritySchema = z.enum(['WARNING', 'ENFORCE']);
export type KnowledgeOntologyConstraintSeverity = z.infer<typeof KnowledgeOntologyConstraintSeveritySchema>;

export const KnowledgeReleaseTagStatusSchema = z.enum(['PROMOTED', 'HOLD', 'RETIRED']);
export type KnowledgeReleaseTagStatus = z.infer<typeof KnowledgeReleaseTagStatusSchema>;

/** / distinct from the contract schemas. @@map preserves existing DB types. */
export const KnowledgeAlertSubscriptionSectionSchema = z.enum(['provenance', 'pipeline', 'recall']);
export type KnowledgeAlertSubscriptionSection = z.infer<typeof KnowledgeAlertSubscriptionSectionSchema>;

export const KnowledgeAlertSubscriptionSeveritySchema = z.enum(['warning', 'critical']);
export type KnowledgeAlertSubscriptionSeverity = z.infer<typeof KnowledgeAlertSubscriptionSeveritySchema>;

export const KnowledgeAlertSubscriptionConditionSchema = z.enum(['chain_broken', 'dead_letter', 'degraded_rate_high']);
export type KnowledgeAlertSubscriptionCondition = z.infer<typeof KnowledgeAlertSubscriptionConditionSchema>;

export const KnowledgeAlertChannelSchema = z.enum(['console', 'webhook']);
export type KnowledgeAlertChannel = z.infer<typeof KnowledgeAlertChannelSchema>;

// ============================================================================
// Enum value arrays (for iteration/validation)
// ============================================================================

export const SexTypeValues = SexTypeSchema.options;
export const FileBucketVendorValues = FileBucketVendorSchema.options;
export const FileEnvTypeValues = FileEnvTypeSchema.options;
export const AuditActionTypeValues = AuditActionTypeSchema.options;
export const KnowledgeSpaceKindValues = KnowledgeSpaceKindSchema.options;
export const KnowledgeSpaceMemberRoleValues = KnowledgeSpaceMemberRoleSchema.options;
export const KnowledgeSourceTypeValues = KnowledgeSourceTypeSchema.options;
export const KnowledgeSourceStatusValues = KnowledgeSourceStatusSchema.options;
export const DocumentStatusValues = DocumentStatusSchema.options;
export const RevisionStatusValues = RevisionStatusSchema.options;
export const MemoryTypeValues = MemoryTypeSchema.options;
export const MemoryStatusValues = MemoryStatusSchema.options;
export const MemoryScopeValues = MemoryScopeSchema.options;
export const MemoryStrategyStatusValues = MemoryStrategyStatusSchema.options;
export const MemoryStrategyTrialOutcomeValues = MemoryStrategyTrialOutcomeSchema.options;
export const MemoryStrategyReplayTaskStatusValues = MemoryStrategyReplayTaskStatusSchema.options;
export const MemoryStrategyReplayPlanStatusValues = MemoryStrategyReplayPlanStatusSchema.options;
export const MemoryStrategyBaselineStatusValues = MemoryStrategyBaselineStatusSchema.options;
export const DocumentPrincipalTypeValues = DocumentPrincipalTypeSchema.options;
export const EnvironmentFactStatusValues = EnvironmentFactStatusSchema.options;
export const MemorySkillStatusValues = MemorySkillStatusSchema.options;
export const DocumentPrincipalPermissionValues = DocumentPrincipalPermissionSchema.options;
export const KnowledgePrincipalTypeValues = KnowledgePrincipalTypeSchema.options;
export const KnowledgePrincipalSourceValues = KnowledgePrincipalSourceSchema.options;
export const KnowledgePrincipalStatusValues = KnowledgePrincipalStatusSchema.options;
export const KnowledgeApiKeyStatusValues = KnowledgeApiKeyStatusSchema.options;
export const KnowledgePolicyApprovalStatusValues = KnowledgePolicyApprovalStatusSchema.options;
export const KnowledgeAclResourceTypeValues = KnowledgeAclResourceTypeSchema.options;
export const KnowledgeAclPermissionValues = KnowledgeAclPermissionSchema.options;
export const IngestionStatusValues = IngestionStatusSchema.options;
export const IntegrationObjectScanStatusValues = IntegrationObjectScanStatusSchema.options;
export const ProjectionKindValues = ProjectionKindSchema.options;
export const ProjectionStatusValues = ProjectionStatusSchema.options;
export const RecallEndpointValues = RecallEndpointSchema.options;
export const HandoffStateValues = HandoffStateSchema.options;
export const MemoryFeedbackKindValues = MemoryFeedbackKindSchema.options;
export const MemoryConflictSeverityValues = MemoryConflictSeveritySchema.options;
export const MemoryExtractionDecisionValues = MemoryExtractionDecisionSchema.options;
export const MemoryExtractionConflictReasonValues = MemoryExtractionConflictReasonSchema.options;
export const MemoryConflictStateValues = MemoryConflictStateSchema.options;
export const MemoryConflictResolutionTypeValues = MemoryConflictResolutionTypeSchema.options;
export const CapabilityKindValues = CapabilityKindSchema.options;
export const CapabilityTrustClassValues = CapabilityTrustClassSchema.options;
export const CapabilityGapStatusValues = CapabilityGapStatusSchema.options;
export const CapabilitySensitivityClassValues = CapabilitySensitivityClassSchema.options;
export const CapabilityProposalStatusValues = CapabilityProposalStatusSchema.options;
export const CapabilityApprovalDecisionValues = CapabilityApprovalDecisionSchema.options;
export const CapabilityProposalOriginValues = CapabilityProposalOriginSchema.options;
export const CapabilityBindingStatusValues = CapabilityBindingStatusSchema.options;
export const CapabilityTrialOutcomeClassValues = CapabilityTrialOutcomeClassSchema.options;
export const UsageRuleStatusValues = UsageRuleStatusSchema.options;
export const EntityStatusValues = EntityStatusSchema.options;
export const RelationStatusValues = RelationStatusSchema.options;
export const EntityMergeStatusValues = EntityMergeStatusSchema.options;
export const ProvenanceEntityTypeValues = ProvenanceEntityTypeSchema.options;
export const ProvenanceActivityTypeValues = ProvenanceActivityTypeSchema.options;
export const ProvenanceActorTypeValues = ProvenanceActorTypeSchema.options;
export const KnowledgePipelineRunStatusValues = KnowledgePipelineRunStatusSchema.options;
export const KnowledgePipelineStepStatusValues = KnowledgePipelineStepStatusSchema.options;
export const KnowledgeDecisionOutcomeValues = KnowledgeDecisionOutcomeSchema.options;
export const KnowledgeDecisionStatusValues = KnowledgeDecisionStatusSchema.options;
export const KnowledgeOntologyStatusValues = KnowledgeOntologyStatusSchema.options;
export const KnowledgeOntologyConstraintSeverityValues = KnowledgeOntologyConstraintSeveritySchema.options;
export const KnowledgeReleaseTagStatusValues = KnowledgeReleaseTagStatusSchema.options;
export const KnowledgeAlertSubscriptionSectionValues = KnowledgeAlertSubscriptionSectionSchema.options;
export const KnowledgeAlertSubscriptionSeverityValues = KnowledgeAlertSubscriptionSeveritySchema.options;
export const KnowledgeAlertSubscriptionConditionValues = KnowledgeAlertSubscriptionConditionSchema.options;
export const KnowledgeAlertChannelValues = KnowledgeAlertChannelSchema.options;

// ============================================================================
// Type guards
// ============================================================================

export const isSexType = (value: unknown): value is SexType => SexTypeSchema.safeParse(value).success;
export const isFileBucketVendor = (value: unknown): value is FileBucketVendor => FileBucketVendorSchema.safeParse(value).success;
export const isFileEnvType = (value: unknown): value is FileEnvType => FileEnvTypeSchema.safeParse(value).success;
export const isAuditActionType = (value: unknown): value is AuditActionType => AuditActionTypeSchema.safeParse(value).success;
export const isKnowledgeSpaceKind = (value: unknown): value is KnowledgeSpaceKind => KnowledgeSpaceKindSchema.safeParse(value).success;
export const isKnowledgeSpaceMemberRole = (value: unknown): value is KnowledgeSpaceMemberRole => KnowledgeSpaceMemberRoleSchema.safeParse(value).success;
export const isKnowledgeSourceType = (value: unknown): value is KnowledgeSourceType => KnowledgeSourceTypeSchema.safeParse(value).success;
export const isKnowledgeSourceStatus = (value: unknown): value is KnowledgeSourceStatus => KnowledgeSourceStatusSchema.safeParse(value).success;
export const isDocumentStatus = (value: unknown): value is DocumentStatus => DocumentStatusSchema.safeParse(value).success;
export const isRevisionStatus = (value: unknown): value is RevisionStatus => RevisionStatusSchema.safeParse(value).success;
export const isMemoryType = (value: unknown): value is MemoryType => MemoryTypeSchema.safeParse(value).success;
export const isMemoryStatus = (value: unknown): value is MemoryStatus => MemoryStatusSchema.safeParse(value).success;
export const isMemoryScope = (value: unknown): value is MemoryScope => MemoryScopeSchema.safeParse(value).success;
export const isMemoryStrategyStatus = (value: unknown): value is MemoryStrategyStatus => MemoryStrategyStatusSchema.safeParse(value).success;
export const isMemoryStrategyTrialOutcome = (value: unknown): value is MemoryStrategyTrialOutcome => MemoryStrategyTrialOutcomeSchema.safeParse(value).success;
export const isMemoryStrategyReplayTaskStatus = (value: unknown): value is MemoryStrategyReplayTaskStatus => MemoryStrategyReplayTaskStatusSchema.safeParse(value).success;
export const isMemoryStrategyReplayPlanStatus = (value: unknown): value is MemoryStrategyReplayPlanStatus => MemoryStrategyReplayPlanStatusSchema.safeParse(value).success;
export const isMemoryStrategyBaselineStatus = (value: unknown): value is MemoryStrategyBaselineStatus => MemoryStrategyBaselineStatusSchema.safeParse(value).success;
export const isDocumentPrincipalType = (value: unknown): value is DocumentPrincipalType => DocumentPrincipalTypeSchema.safeParse(value).success;
export const isEnvironmentFactStatus = (value: unknown): value is EnvironmentFactStatus => EnvironmentFactStatusSchema.safeParse(value).success;
export const isMemorySkillStatus = (value: unknown): value is MemorySkillStatus => MemorySkillStatusSchema.safeParse(value).success;
export const isDocumentPrincipalPermission = (value: unknown): value is DocumentPrincipalPermission => DocumentPrincipalPermissionSchema.safeParse(value).success;
export const isKnowledgePrincipalType = (value: unknown): value is KnowledgePrincipalType => KnowledgePrincipalTypeSchema.safeParse(value).success;
export const isKnowledgePrincipalSource = (value: unknown): value is KnowledgePrincipalSource => KnowledgePrincipalSourceSchema.safeParse(value).success;
export const isKnowledgePrincipalStatus = (value: unknown): value is KnowledgePrincipalStatus => KnowledgePrincipalStatusSchema.safeParse(value).success;
export const isKnowledgeApiKeyStatus = (value: unknown): value is KnowledgeApiKeyStatus => KnowledgeApiKeyStatusSchema.safeParse(value).success;
export const isKnowledgePolicyApprovalStatus = (value: unknown): value is KnowledgePolicyApprovalStatus => KnowledgePolicyApprovalStatusSchema.safeParse(value).success;
export const isKnowledgeAclResourceType = (value: unknown): value is KnowledgeAclResourceType => KnowledgeAclResourceTypeSchema.safeParse(value).success;
export const isKnowledgeAclPermission = (value: unknown): value is KnowledgeAclPermission => KnowledgeAclPermissionSchema.safeParse(value).success;
export const isIngestionStatus = (value: unknown): value is IngestionStatus => IngestionStatusSchema.safeParse(value).success;
export const isIntegrationObjectScanStatus = (value: unknown): value is IntegrationObjectScanStatus => IntegrationObjectScanStatusSchema.safeParse(value).success;
export const isProjectionKind = (value: unknown): value is ProjectionKind => ProjectionKindSchema.safeParse(value).success;
export const isProjectionStatus = (value: unknown): value is ProjectionStatus => ProjectionStatusSchema.safeParse(value).success;
export const isRecallEndpoint = (value: unknown): value is RecallEndpoint => RecallEndpointSchema.safeParse(value).success;
export const isHandoffState = (value: unknown): value is HandoffState => HandoffStateSchema.safeParse(value).success;
export const isMemoryFeedbackKind = (value: unknown): value is MemoryFeedbackKind => MemoryFeedbackKindSchema.safeParse(value).success;
export const isMemoryConflictSeverity = (value: unknown): value is MemoryConflictSeverity => MemoryConflictSeveritySchema.safeParse(value).success;
export const isMemoryExtractionDecision = (value: unknown): value is MemoryExtractionDecision => MemoryExtractionDecisionSchema.safeParse(value).success;
export const isMemoryExtractionConflictReason = (value: unknown): value is MemoryExtractionConflictReason => MemoryExtractionConflictReasonSchema.safeParse(value).success;
export const isMemoryConflictState = (value: unknown): value is MemoryConflictState => MemoryConflictStateSchema.safeParse(value).success;
export const isMemoryConflictResolutionType = (value: unknown): value is MemoryConflictResolutionType => MemoryConflictResolutionTypeSchema.safeParse(value).success;
export const isCapabilityKind = (value: unknown): value is CapabilityKind => CapabilityKindSchema.safeParse(value).success;
export const isCapabilityTrustClass = (value: unknown): value is CapabilityTrustClass => CapabilityTrustClassSchema.safeParse(value).success;
export const isCapabilityGapStatus = (value: unknown): value is CapabilityGapStatus => CapabilityGapStatusSchema.safeParse(value).success;
export const isCapabilitySensitivityClass = (value: unknown): value is CapabilitySensitivityClass => CapabilitySensitivityClassSchema.safeParse(value).success;
export const isCapabilityProposalStatus = (value: unknown): value is CapabilityProposalStatus => CapabilityProposalStatusSchema.safeParse(value).success;
export const isCapabilityApprovalDecision = (value: unknown): value is CapabilityApprovalDecision => CapabilityApprovalDecisionSchema.safeParse(value).success;
export const isCapabilityProposalOrigin = (value: unknown): value is CapabilityProposalOrigin => CapabilityProposalOriginSchema.safeParse(value).success;
export const isCapabilityBindingStatus = (value: unknown): value is CapabilityBindingStatus => CapabilityBindingStatusSchema.safeParse(value).success;
export const isCapabilityTrialOutcomeClass = (value: unknown): value is CapabilityTrialOutcomeClass => CapabilityTrialOutcomeClassSchema.safeParse(value).success;
export const isUsageRuleStatus = (value: unknown): value is UsageRuleStatus => UsageRuleStatusSchema.safeParse(value).success;
export const isEntityStatus = (value: unknown): value is EntityStatus => EntityStatusSchema.safeParse(value).success;
export const isRelationStatus = (value: unknown): value is RelationStatus => RelationStatusSchema.safeParse(value).success;
export const isEntityMergeStatus = (value: unknown): value is EntityMergeStatus => EntityMergeStatusSchema.safeParse(value).success;
export const isProvenanceEntityType = (value: unknown): value is ProvenanceEntityType => ProvenanceEntityTypeSchema.safeParse(value).success;
export const isProvenanceActivityType = (value: unknown): value is ProvenanceActivityType => ProvenanceActivityTypeSchema.safeParse(value).success;
export const isProvenanceActorType = (value: unknown): value is ProvenanceActorType => ProvenanceActorTypeSchema.safeParse(value).success;
export const isKnowledgePipelineRunStatus = (value: unknown): value is KnowledgePipelineRunStatus => KnowledgePipelineRunStatusSchema.safeParse(value).success;
export const isKnowledgePipelineStepStatus = (value: unknown): value is KnowledgePipelineStepStatus => KnowledgePipelineStepStatusSchema.safeParse(value).success;
export const isKnowledgeDecisionOutcome = (value: unknown): value is KnowledgeDecisionOutcome => KnowledgeDecisionOutcomeSchema.safeParse(value).success;
export const isKnowledgeDecisionStatus = (value: unknown): value is KnowledgeDecisionStatus => KnowledgeDecisionStatusSchema.safeParse(value).success;
export const isKnowledgeOntologyStatus = (value: unknown): value is KnowledgeOntologyStatus => KnowledgeOntologyStatusSchema.safeParse(value).success;
export const isKnowledgeOntologyConstraintSeverity = (value: unknown): value is KnowledgeOntologyConstraintSeverity => KnowledgeOntologyConstraintSeveritySchema.safeParse(value).success;
export const isKnowledgeReleaseTagStatus = (value: unknown): value is KnowledgeReleaseTagStatus => KnowledgeReleaseTagStatusSchema.safeParse(value).success;
export const isKnowledgeAlertSubscriptionSection = (value: unknown): value is KnowledgeAlertSubscriptionSection => KnowledgeAlertSubscriptionSectionSchema.safeParse(value).success;
export const isKnowledgeAlertSubscriptionSeverity = (value: unknown): value is KnowledgeAlertSubscriptionSeverity => KnowledgeAlertSubscriptionSeveritySchema.safeParse(value).success;
export const isKnowledgeAlertSubscriptionCondition = (value: unknown): value is KnowledgeAlertSubscriptionCondition => KnowledgeAlertSubscriptionConditionSchema.safeParse(value).success;
export const isKnowledgeAlertChannel = (value: unknown): value is KnowledgeAlertChannel => KnowledgeAlertChannelSchema.safeParse(value).success;
