/** Generated by scripts/generate-brand-module.mjs from brand/brand.config.json. Do not edit directly. */

/** Build-time white-label variant, widened so either brand's sources typecheck. */
export type BrandVariant = 'sensteed'

/** Build-time white-label variant. */
export const BRAND_VARIANT: BrandVariant = "sensteed"

/** Tenant identity bound to the build-time brand. */
export const BRAND_TENANT = "sensteed" as const

/** Stable tenant id accepted by the activation gate for this brand only. */
export const BRAND_TENANT_ID = "7a8866f9-3994-4341-ade6-b9fa942efe99" as const

/** Display names shown in chrome that is identical across release channels. */
export const BRAND_DISPLAY_NAME = Object.freeze({
  titlebar: "哪吒Agent",
  locale: "哪吒Agent",
})

/** Version service contract shared with the shell identity. */
export const BRAND_UPDATE_SERVICE = Object.freeze({
  endpoint: "https://ai.hozonauto.com/api/desktop/version",
  versionHeader: "X-Sensteed-Agent-Version",
  channelHeader: "X-Sensteed-Agent-Channel",
})
