import { BRAND_DISPLAY_NAME } from '../generated-product-identity.ts'

export type DofeAccessKey = 'MODELS_API_KEY'
export const DOFE_ACCESS_KEY: DofeAccessKey = 'MODELS_API_KEY'

const PRODUCT_NAME = BRAND_DISPLAY_NAME.locale
const PRODUCT_EYEBROW = BRAND_DISPLAY_NAME.titlebar
const TENANT_LABEL_ZH = '山子 Agent（Sensteed）'
const TENANT_LABEL_EN = 'Sensteed'

export const DOFE_ACCESS_COPY = {
  zh: {
    nav: '用户设置', title: '用户设置', loginSuccess: '登录成功，模型设置已保存，可以开始使用了。', intro: '一次输入 Model API Key，统一连接 CI Model Router 和内置 DoFe 插件。', key: 'Model API Key', placeholder: '输入 model_api_key', save: '验证并进入', remove: '移除', configured: '已配置', missing: '未配置', saving: '正在验证…', removing: '移除中…', loadModels: '获取可用模型', loadingModels: '正在获取模型…', protocolTitle: '接口协议', protocolChat: 'OpenAI Chat Completions', protocolMessages: 'Anthropic Messages', modelsTitle: '选择默认模型', modelsPlaceholder: '获取模型列表后在此选择', modelsEmpty: '该协议下没有可用模型。', modelsError: '暂时无法获取当前协议的模型列表，请确认 ixicai.cn 服务可用。', tenantMismatch: `该 Key 不属于${TENANT_LABEL_ZH}租户，请使用当前产品管理员分配的 model_api_key。`, tenantUnavailable: '暂时无法确认该 Key 的租户归属，请稍后重试。', modelRequired: '请选择一个与接口协议匹配的可用模型。', loadError: '暂时无法读取凭据状态。', invalidKey: 'Key 无法通过模型网关验证，请检查后重试。', saveError: '保存失败，请检查 Key、协议和模型后重试。', removeError: '退出登录失败，请稍后重试。', storedReady: '已使用保存的凭据，可直接刷新当前协议的模型列表。', sensteedLoginTitle: '登录 Sensteed Agent', sensteedLoginIntro: '请先完成飞书登录，登录成功后再设置模型和内置能力。', sensteedSetupTitle: '设置 Sensteed Agent', sensteedSetupIntro: '登录已完成，请选择接口协议、默认模型和需要启用的内置能力。', onboardingEyebrow: PRODUCT_EYEBROW, onboardingTitle: `激活 ${PRODUCT_NAME}`, onboardingIntro: `验证访问凭据、选择接口协议、默认模型和需要的 DoFe 能力，完成后即可进入${PRODUCT_NAME}工作区。`, onboardingHelp: '获取 model_api_key，请联系山子高科管理员。', credentialHint: '验证通过后保存到系统凭据存储', pluginsTitle: '启用内置能力', selectedCount: '已选择 {count} 项', showKey: '显示 Key', hideKey: '隐藏 Key', later: '稍后设置',
    pluginStateBuiltIn: '已内置启用', pluginStateEnabled: '已启用', pluginStateUnentitled: '未开通', pluginStateDisabled: '未启用', pluginServersTitle: 'MCP 数据源', pluginStateTitle: '当前状态', pluginNoServer: '内置调研通道，不经过 MCP。', pluginManageHint: '在 设置 → 用户设置 中调整这些能力的开关。',
  },
  en: {
    nav: 'User settings', title: 'User settings', loginSuccess: 'Login successful. Model settings saved. You are ready to go.', intro: 'Enter one Model API key to connect the CI Model Router and built-in DoFe plugins.', key: 'Model API key', placeholder: 'Enter model_api_key', save: 'Verify and enter', remove: 'Remove', configured: 'Configured', missing: 'Not configured', saving: 'Verifying…', removing: 'Removing…', loadModels: 'Load available models', loadingModels: 'Loading models…', protocolTitle: 'API protocol', protocolChat: 'OpenAI Chat Completions', protocolMessages: 'Anthropic Messages', modelsTitle: 'Choose default model', modelsPlaceholder: 'Choose a model after loading the list', modelsEmpty: 'No models are available for this protocol.', modelsError: 'Could not load models for this protocol from ixicai.cn.', tenantMismatch: `This key belongs to a different tenant. Use a ${TENANT_LABEL_EN} model_api_key.`, tenantUnavailable: 'The key tenant could not be confirmed. Try again shortly.', modelRequired: 'Choose a model compatible with the selected protocol.', loadError: 'Credential status is temporarily unavailable.', invalidKey: 'The key could not be verified by the model gateway.', saveError: 'Could not save the key, protocol, and plugin selection. Check them and try again.', removeError: 'Could not log out. Try again shortly.', storedReady: 'Using your saved credential. Refresh the model list for this protocol.', sensteedLoginTitle: 'Log in to Sensteed Agent', sensteedLoginIntro: 'Complete Feishu login first. After login, configure the model and built-in capabilities.', sensteedSetupTitle: 'Set up Sensteed Agent', sensteedSetupIntro: 'Login completed. Choose the API protocol, default model, and built-in capabilities to enable.', onboardingEyebrow: PRODUCT_EYEBROW, onboardingTitle: `Activate ${PRODUCT_NAME}`, onboardingIntro: `Verify your access credential, choose an API protocol, choose a default model, and select the DoFe capabilities you need in ${PRODUCT_NAME}.`, onboardingHelp: `For a model_api_key, contact the ${PRODUCT_NAME} support team.`, credentialHint: 'Saved to the system credential store after verification', pluginsTitle: 'Enable built-in capabilities', selectedCount: '{count} selected', showKey: 'Show key', hideKey: 'Hide key', later: 'Set up later',
    pluginStateBuiltIn: 'Built in', pluginStateEnabled: 'Enabled', pluginStateUnentitled: 'Not entitled', pluginStateDisabled: 'Off', pluginServersTitle: 'MCP data sources', pluginStateTitle: 'Status', pluginNoServer: 'Built-in research channel; no MCP transport.', pluginManageHint: 'Turn these capabilities on or off in Settings → User settings.',
  },
} as const

export type DofeAccessLocaleKey = keyof typeof DOFE_ACCESS_COPY.en
