// 片段 4/7：样式系统。
// dsw token 映射前端四色语义：rose=error / amber=warn / emerald=success / sky+blue=business。
// pill/徽章底色用 color-mix 低透明度，浅色/深色皮肤均由宿主 token 适配。
const css = `
.sf-root{--sf-rose:var(--dsw-alias-state-error-primary);--sf-amber:var(--dsw-alias-state-warn-primary);--sf-green:var(--dsw-alias-state-success-primary);--sf-blue:var(--dsw-alias-state-business-primary);--sf-sky:var(--dsw-alias-state-business-primary);--sf-line:var(--dsw-alias-border-l1);--sf-line2:var(--dsw-alias-border-l2);--sf-bg:color-mix(in srgb,var(--dsw-alias-bg-layer-2) 45%,var(--dsw-alias-bg-base));--sf-card:var(--dsw-alias-bg-base);--sf-hover:var(--dsw-alias-bg-layer-2);--sf-ink:var(--dsw-alias-label-primary);--sf-ink2:var(--dsw-alias-label-secondary);--sf-ink3:var(--dsw-alias-label-tertiary);--sf-on-brand:var(--dsw-alias-label-primary-foreground)}
/* 品牌轴对齐 datasource 网页端浅绿工作台（agentspace 系）；暗色皮肤提亮保持对比度 */
.sf-root{--sf-brand:oklch(0.55 0.14 162)}[data-ds-dark-theme] .sf-root{--sf-brand:oklch(0.74 0.11 162)}
.sf-button{display:flex;width:36px;height:36px;align-items:center;justify-content:center;gap:8px;border:0;border-radius:6px;background:transparent;color:var(--sf-ink2);cursor:pointer}.sf-button:hover{background:var(--sf-hover);color:var(--sf-ink)}.sf-wide{width:100%;height:34px;justify-content:flex-start;padding:0 10px}.sf-wide span{font-size:13px}
.sf-overlay{position:fixed;inset:0;z-index:510;background:var(--sf-bg);color:var(--sf-ink);font-size:13px}.sf-shell{display:grid;grid-template-rows:auto auto 1fr;width:100%;height:100%;overflow:hidden}
.sf-header{display:flex;min-height:72px;align-items:flex-end;justify-content:space-between;gap:18px;padding:14px 28px 16px;border-bottom:1px solid var(--sf-line);flex-wrap:wrap}.sf-header-main{min-width:0}.sf-eyebrow{margin:0 0 2px;color:var(--sf-ink3);font-size:11px;font-weight:650;letter-spacing:.06em;text-transform:uppercase}.sf-header h1{margin:0;font-size:20px;line-height:1.35;font-weight:650}.sf-desc{margin:2px 0 0;color:var(--sf-ink2);font-size:12.5px}.sf-header-side{display:flex;align-items:flex-end;gap:10px;flex-wrap:wrap}.sf-filter{display:grid;gap:4px}.sf-filter>span{color:var(--sf-ink3);font-size:11px}.sf-filter select{min-width:130px;height:30px;padding:4px 10px;border:1px solid var(--sf-line2);border-radius:6px;background:var(--sf-card);color:inherit;font:inherit;font-size:12.5px;cursor:pointer}.sf-header-buttons{display:flex;gap:6px}
.sf-icon-button{display:grid;width:36px;height:36px;place-items:center;border:1px solid var(--sf-line);border-radius:6px;background:var(--sf-card);color:inherit;cursor:pointer}.sf-icon-button:hover{background:var(--sf-hover)}

.sf-tabs{display:inline-flex;gap:2px;margin:12px 28px 0;padding:3px;border:1px solid var(--sf-line);border-radius:8px;background:color-mix(in srgb,var(--dsw-alias-bg-layer-2) 62%,transparent);width:fit-content;max-width:calc(100% - 56px);overflow-x:auto}.sf-tabs button{height:30px;padding:0 14px;border:0;border-radius:6px;background:transparent;color:var(--sf-ink2);font:inherit;font-size:12.5px;white-space:nowrap;cursor:pointer}.sf-tabs button[aria-current]{background:var(--sf-card);color:var(--sf-ink);font-weight:650;box-shadow:0 1px 2px color-mix(in srgb,var(--sf-ink) 8%,transparent)}
.sf-content{overflow:auto;padding:16px 28px 44px}.sf-content.sf-refreshing{opacity:.62;transition:opacity .2s}
.sf-view{display:grid;gap:16px;max-width:1680px;margin:0 auto}
/* 卡片：去阴影直角 + 标题分隔线（对齐前端 Card 约定） */
.sf-card{min-width:0;border:1px solid var(--sf-line);border-radius:8px;background:var(--sf-card)}.sf-card-head{display:flex;align-items:center;gap:10px;padding:12px 16px;border-bottom:1px solid var(--sf-line)}.sf-card-head h2{margin:0;font-size:13px;font-weight:650}.sf-card-unit{color:var(--sf-ink3);font-size:11px}.sf-card-actions{display:flex;align-items:center;gap:8px;margin-left:auto}.sf-card-body{padding:12px 16px}.sf-card-body.is-flush{padding:0}
/* KPI 卡 */
.sf-kpis{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:12px}.sf-kpi{display:grid;gap:6px;align-content:start;padding:14px 16px;border:1px solid var(--sf-line);border-radius:8px;background:var(--sf-card)}.sf-kpi.is-clickable{cursor:pointer;transition:border-color .15s}.sf-kpi.is-clickable:hover{border-color:var(--sf-brand)}.sf-kpi-top{display:flex;align-items:center;justify-content:space-between}.sf-kpi-label{color:var(--sf-ink2);font-size:12px}.sf-kpi-icon{display:grid;width:32px;height:32px;place-items:center;border:1px solid var(--sf-line);border-radius:6px;background:color-mix(in srgb,var(--sf-hover) 55%,transparent);color:color-mix(in srgb,var(--sf-ink) 70%,var(--sf-ink2))}.sf-kpi-value{font-size:20px;line-height:1.2;font-weight:650;font-variant-numeric:tabular-nums;overflow-wrap:anywhere}.sf-kpi.is-neg .sf-kpi-value{color:color-mix(in srgb,var(--sf-rose) 70%,var(--sf-ink))}.sf-kpi-hint{color:var(--sf-ink3);font-size:11px}.sf-hint-up{color:color-mix(in srgb,var(--sf-green) 75%,var(--sf-ink))}.sf-hint-down{color:color-mix(in srgb,var(--sf-rose) 75%,var(--sf-ink))}.sf-hint-warn{color:color-mix(in srgb,var(--sf-amber) 75%,var(--sf-ink))}
/* 统计卡（预警中心）：可点击筛选，激活 ring */
.sf-stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.sf-stat{display:grid;gap:2px;justify-items:start;padding:12px 14px;border:1px solid var(--sf-line);border-radius:8px;background:var(--sf-card);color:inherit;font:inherit;text-align:left}.sf-stat.is-clickable{cursor:pointer}.sf-stat.is-active{box-shadow:0 0 0 2px var(--sf-brand)}.sf-stat strong{font-size:20px;font-variant-numeric:tabular-nums}.sf-stat span{color:var(--sf-ink2);font-size:12px}.sf-stat-rose strong{color:color-mix(in srgb,var(--sf-rose) 75%,var(--sf-ink))}.sf-stat-amber strong{color:color-mix(in srgb,var(--sf-amber) 75%,var(--sf-ink))}.sf-stat-sky strong{color:color-mix(in srgb,var(--sf-sky) 75%,var(--sf-ink))}.sf-stat-green strong{color:color-mix(in srgb,var(--sf-green) 75%,var(--sf-ink))}
/* 徽章与 pill */
.sf-badge{display:inline-flex;align-items:center;padding:1px 8px;border-radius:999px;border:1px solid var(--sf-line);font-size:11px;color:var(--sf-ink2)}.sf-badge-rose{color:color-mix(in srgb,var(--sf-rose) 75%,var(--sf-ink));border-color:color-mix(in srgb,var(--sf-rose) 35%,transparent)}.sf-badge-amber{color:color-mix(in srgb,var(--sf-amber) 75%,var(--sf-ink));border-color:color-mix(in srgb,var(--sf-amber) 35%,transparent)}.sf-badge-green{color:color-mix(in srgb,var(--sf-green) 75%,var(--sf-ink));border-color:color-mix(in srgb,var(--sf-green) 35%,transparent)}.sf-badge-blue,.sf-badge-sky{color:color-mix(in srgb,var(--sf-blue) 75%,var(--sf-ink));border-color:color-mix(in srgb,var(--sf-blue) 35%,transparent)}
.sf-pill{display:inline-flex;align-items:center;padding:2px 9px;border-radius:999px;font-size:11px;white-space:nowrap}.sf-pill-muted{background:var(--sf-hover);color:var(--sf-ink2)}.sf-pill-rose{background:color-mix(in srgb,var(--sf-rose) 14%,transparent);color:color-mix(in srgb,var(--sf-rose) 78%,var(--sf-ink))}.sf-pill-amber{background:color-mix(in srgb,var(--sf-amber) 16%,transparent);color:color-mix(in srgb,var(--sf-amber) 78%,var(--sf-ink))}.sf-pill-green{background:color-mix(in srgb,var(--sf-green) 14%,transparent);color:color-mix(in srgb,var(--sf-green) 78%,var(--sf-ink))}.sf-pill-blue{background:color-mix(in srgb,var(--sf-blue) 14%,transparent);color:color-mix(in srgb,var(--sf-blue) 78%,var(--sf-ink))}
/* 表格：无斑马纹，行 border-b + hover，数字右对齐，可选 sticky 首列 */
.sf-table-scroll{max-width:100%;overflow-x:auto}.sf-table{width:100%;border-collapse:collapse;font-size:12px;font-variant-numeric:tabular-nums}.sf-table th,.sf-table td{padding:8px 10px;border-bottom:1px solid var(--sf-line);text-align:right;white-space:nowrap}.sf-table th:first-child,.sf-table td:first-child{text-align:left}.sf-table th{color:var(--sf-ink3);font-weight:500;font-size:11px}.sf-table tbody tr{background:transparent}.sf-table tbody tr:hover{background:var(--sf-hover)}.sf-table tbody tr:last-child td{border-bottom:0}.sf-table tr.is-clickable{cursor:pointer}.sf-num{font-variant-numeric:tabular-nums}.sf-sticky-col{position:sticky;left:0;background:var(--sf-card);z-index:1;text-align:left}.sf-table tbody tr:hover .sf-sticky-col{background:var(--sf-hover)}
.sf-table-wrap{display:grid;gap:4px}.sf-table-toolbar{display:flex;align-items:center;justify-content:space-between;gap:8px;min-height:28px;color:var(--sf-ink3);font-size:11px}.sf-table-fields{position:relative}.sf-table-tool{display:inline-flex;align-items:center;gap:5px;padding:5px 8px;border:1px solid var(--sf-line2);border-radius:6px;background:var(--sf-card);color:var(--sf-ink2);cursor:pointer;list-style:none}.sf-table-tool::-webkit-details-marker{display:none}.sf-table-fields[open] .sf-table-tool{border-color:var(--sf-brand);color:var(--sf-brand)}.sf-table-fields-menu{position:absolute;top:34px;left:0;z-index:4;display:grid;gap:6px;min-width:180px;padding:10px;border:1px solid var(--sf-line2);border-radius:8px;background:var(--sf-card);box-shadow:0 8px 24px color-mix(in srgb,var(--sf-ink) 12%,transparent)}.sf-table-fields-menu strong{font-size:12px;color:var(--sf-ink)}.sf-table-fields-hint{color:var(--sf-ink3);font-size:10px}.sf-table-field-option{display:flex;align-items:center;gap:7px;padding:3px 0;color:var(--sf-ink2);cursor:pointer}.sf-table-field-option input{accent-color:var(--sf-brand)}.sf-table-sort-note{margin-left:auto}.sf-table-sort-button{display:inline-flex;align-items:center;gap:4px;padding:0;border:0;background:transparent;color:inherit;font:inherit;font-weight:600;cursor:pointer}.sf-table-sort-button:hover,.sf-table-sort-button:focus-visible{color:var(--sf-brand)}.sf-link-button{padding:0;border:0;background:transparent;color:var(--sf-brand);font:inherit;text-align:left;cursor:pointer}
/* 热力格（执行率） */
.sf-heat{display:inline-flex;align-items:center;padding:2px 8px;border-radius:6px;font-weight:650}.sf-heat-over{background:color-mix(in srgb,var(--sf-rose) 16%,transparent);color:color-mix(in srgb,var(--sf-rose) 80%,var(--sf-ink))}.sf-heat-healthy{background:color-mix(in srgb,var(--sf-green) 14%,transparent);color:color-mix(in srgb,var(--sf-green) 80%,var(--sf-ink))}.sf-heat-slow{background:color-mix(in srgb,var(--sf-amber) 16%,transparent);color:color-mix(in srgb,var(--sf-amber) 80%,var(--sf-ink))}.sf-heat-early{background:var(--sf-hover);color:var(--sf-ink2)}
.sf-neg{color:color-mix(in srgb,var(--sf-rose) 70%,var(--sf-ink));font-weight:650}.sf-pos{color:color-mix(in srgb,var(--sf-green) 70%,var(--sf-ink))}
/* 进度条 */
.sf-progress{height:6px;min-width:80px;border-radius:4px;background:var(--sf-hover);overflow:hidden}.sf-progress-fill{height:100%;border-radius:4px;background:var(--sf-brand)}.sf-progress-fill.is-green{background:var(--sf-green)}.sf-progress-fill.is-amber{background:var(--sf-amber)}.sf-progress-fill.is-rose{background:var(--sf-rose)}
/* pill 页签 */
.sf-pilltabs{display:inline-flex;flex-wrap:wrap;gap:2px;padding:2px;border:1px solid var(--sf-line);border-radius:8px;background:var(--sf-card)}.sf-pilltabs button{min-width:72px;height:28px;padding:0 12px;border:0;border-radius:6px;background:transparent;color:var(--sf-ink2);font:inherit;font-size:12px;cursor:pointer}.sf-pilltabs button.is-active{background:var(--sf-ink);color:var(--sf-bg);font-weight:650}
/* 表单 */
.sf-form{display:grid;gap:12px;max-width:640px}.sf-form-row{display:grid;grid-template-columns:140px minmax(0,1fr);align-items:center;gap:12px}.sf-form-row>span{color:var(--sf-ink2);font-size:12px}.sf-form-row input,.sf-form-row select,.sf-form-row textarea{min-height:30px;padding:4px 10px;border:1px solid var(--sf-line2);border-radius:6px;background:var(--sf-card);color:inherit;font:inherit;font-size:13px}.sf-form-row textarea{min-height:56px;resize:vertical}.sf-form-actions{display:flex;align-items:center;gap:12px}
.sf-custom-select,.sf-search-select{display:grid;gap:6px}.sf-custom-select input,.sf-custom-select select,.sf-search-select input,.sf-search-select select{width:100%}.sf-search-select input{min-height:30px;padding:4px 10px;border:1px solid var(--sf-line2);border-radius:6px;background:var(--sf-card);color:inherit;font:inherit;font-size:12px}.sf-search-custom{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:5px 8px;border:1px solid color-mix(in srgb,var(--sf-brand) 35%,var(--sf-line2));border-radius:6px;background:color-mix(in srgb,var(--sf-brand) 8%,var(--sf-card));color:var(--sf-brand);font:inherit;font-size:11px;text-align:left;cursor:pointer}.sf-search-custom:hover{background:color-mix(in srgb,var(--sf-brand) 14%,var(--sf-card))}
.sf-btn{display:inline-flex;align-items:center;gap:6px;height:30px;padding:0 14px;border-radius:6px;border:1px solid transparent;font:inherit;font-size:12.5px;cursor:pointer}.sf-btn:disabled{opacity:.5;cursor:default}.sf-btn-primary{border:0;background:var(--sf-brand);color:var(--sf-on-brand);font-weight:600}.sf-btn-ghost{border-color:var(--sf-line2);background:var(--sf-card);color:inherit}.sf-btn-ghost:hover{background:var(--sf-hover)}.sf-link{border:0;background:transparent;color:var(--sf-brand);font:inherit;font-size:12px;cursor:pointer;text-decoration:underline;padding:0}
.sf-switch{position:relative;display:inline-block;width:34px;height:19px;border:0;border-radius:999px;background:var(--sf-hover);cursor:pointer;transition:background .15s}.sf-switch.is-on{background:var(--sf-green)}.sf-switch-knob{position:absolute;top:2px;left:2px;width:15px;height:15px;border-radius:50%;background:var(--sf-card);transition:left .15s}.sf-switch.is-on .sf-switch-knob{left:17px}
/* Dialog */
.sf-dialog-mask{position:fixed;inset:0;z-index:20;display:grid;place-items:center;background:color-mix(in srgb,var(--sf-bg) 55%,transparent);backdrop-filter:blur(2px)}.sf-dialog{display:grid;grid-template-rows:auto 1fr auto;max-height:82vh;max-width:92vw;border:1px solid var(--sf-line);border-radius:10px;background:var(--sf-card);box-shadow:0 18px 48px color-mix(in srgb,var(--sf-ink) 18%,transparent);outline:none}.sf-dialog-sm{width:420px}.sf-dialog-md{width:640px}.sf-dialog-lg{width:920px}.sf-dialog-head{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:14px 18px;border-bottom:1px solid var(--sf-line)}.sf-dialog-head h3{margin:0;font-size:14px}.sf-dialog-body{padding:16px 18px;overflow:auto}.sf-dialog-foot{display:flex;justify-content:flex-end;gap:10px;padding:12px 18px;border-top:1px solid var(--sf-line)}
/* 图表 */
.sf-chart-wrap{display:grid;gap:10px}.sf-chart-legend{display:flex;justify-content:flex-end;gap:14px;color:var(--sf-ink2);font-size:11px}.sf-chart-legend span{display:inline-flex;align-items:center;gap:5px}.sf-legend{display:inline-block;width:12px;height:8px;border-radius:2px}.sf-legend-a{background:var(--sf-brand)}.sf-legend-b{background:color-mix(in srgb,var(--sf-brand) 45%,transparent)}.sf-legend-c{background:color-mix(in srgb,var(--sf-green) 70%,transparent)}.sf-legend-rose{background:var(--sf-rose)}.sf-legend-amber{background:var(--sf-amber)}.sf-legend-green{background:var(--sf-green)}.sf-legend-blue{background:var(--sf-blue)}
.sf-chart{width:100%;height:auto;min-height:170px;overflow:visible}.sf-grid-line{stroke:var(--sf-line);stroke-width:1}.sf-bar-a{fill:var(--sf-brand)}.sf-bar-b{fill:color-mix(in srgb,var(--sf-brand) 45%,transparent)}.sf-bar-c{fill:color-mix(in srgb,var(--sf-green) 70%,transparent)}.sf-bar-group.is-clickable{cursor:pointer}.sf-bar-group.is-clickable:hover .sf-bar{opacity:.8}.sf-chart-label{fill:var(--sf-ink3);font-size:11px}
/* 瀑布 / 占比 / 净额 */
.sf-waterfall{display:flex;align-items:flex-end;gap:18px;min-height:170px;padding:6px 2px;overflow-x:auto}.sf-waterfall-item{display:grid;gap:4px;justify-items:center;min-width:64px}.sf-waterfall-bar-area{display:flex;align-items:flex-end;height:110px;width:34px;border-bottom:1px solid var(--sf-line)}.sf-waterfall-bar{width:100%;border-radius:4px 4px 0 0;background:var(--sf-brand)}.sf-waterfall-bar.is-rose{background:var(--sf-rose)}.sf-waterfall-bar.is-green{background:var(--sf-green)}.sf-waterfall-bar.is-amber{background:var(--sf-amber)}.sf-waterfall-label{color:var(--sf-ink2);font-size:11px}.sf-waterfall-value{font-size:11px;font-variant-numeric:tabular-nums}
.sf-share{display:grid;gap:10px}.sf-share-track{display:flex;height:14px;border-radius:6px;overflow:hidden}.sf-share-seg{height:100%}.sf-share-seg.is-a{background:var(--sf-brand)}.sf-share-seg.is-b{background:color-mix(in srgb,var(--sf-brand) 45%,transparent)}.sf-share-seg.is-c{background:color-mix(in srgb,var(--sf-green) 70%,transparent)}.sf-share-seg.is-d{background:color-mix(in srgb,var(--sf-amber) 60%,transparent)}.sf-share-legend{display:flex;flex-wrap:wrap;gap:12px;color:var(--sf-ink2);font-size:11px}.sf-share-legend span{display:inline-flex;align-items:center;gap:5px}
.sf-netbars{display:grid;gap:6px}.sf-netbar-row{display:grid;grid-template-columns:64px 1fr 76px;align-items:center;gap:10px}.sf-netbar-label{color:var(--sf-ink2);font-size:11px}.sf-netbar-track{display:flex;height:12px}.sf-netbar-half{display:flex;flex:1}.sf-netbar-half.is-left{justify-content:flex-end}.sf-netbar-zero{width:1px;background:var(--sf-line2)}.sf-netbar-bar{height:100%;border-radius:3px}.sf-netbar-bar.is-green{background:var(--sf-green)}.sf-netbar-bar.is-rose{background:var(--sf-rose)}.sf-netbar-value{text-align:right;font-size:11px;font-variant-numeric:tabular-nums}
/* 口径条（网页端 bg-card 边框说明条）与总览非对称双栏（趋势 1.2fr / 主体 0.8fr） */
.sf-scopebar{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap;padding:8px 12px;border:1px solid var(--sf-line);border-radius:8px;background:var(--sf-card);color:var(--sf-ink2);font-size:12px}.sf-overview-grid{display:grid;gap:16px;grid-template-columns:minmax(0,1.2fr) minmax(320px,.8fr)}
/* 布局辅助 */
.sf-two-col{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.sf-stack{display:grid;gap:16px;min-width:0}.sf-row{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.sf-row-between{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap}.sf-filters{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,max-content));gap:10px;align-items:center}.sf-budget-filters{flex:1 1 600px;min-width:0;grid-template-columns:repeat(auto-fit,minmax(min(150px,100%),1fr))}
/* 提示与状态 */
.sf-notice{margin:0;color:var(--sf-ink2);font-size:12px}.sf-notice-rose{color:color-mix(in srgb,var(--sf-rose) 75%,var(--sf-ink))}.sf-notice-green{color:color-mix(in srgb,var(--sf-green) 75%,var(--sf-ink))}.sf-banner{display:flex;align-items:center;gap:10px;padding:10px 14px;border-radius:8px;font-size:12.5px}.sf-banner-amber{background:color-mix(in srgb,var(--sf-amber) 12%,transparent);color:color-mix(in srgb,var(--sf-amber) 80%,var(--sf-ink))}.sf-banner-green{background:color-mix(in srgb,var(--sf-green) 12%,transparent);color:color-mix(in srgb,var(--sf-green) 80%,var(--sf-ink))}.sf-banner .sf-btn{margin-left:auto}
.sf-note{margin:0;color:var(--sf-ink3);font-size:12px;line-height:1.55}.sf-empty,.sf-loading,.sf-fatal{display:grid;min-height:110px;place-items:center;align-content:center;gap:8px;color:var(--sf-ink2);font-size:13px;text-align:center}
/* 证据快照数字网格 */
.sf-evidence{display:grid;grid-template-columns:repeat(auto-fill,minmax(150px,1fr));gap:8px}.sf-evidence-item{padding:8px 10px;border:1px solid var(--sf-line);border-radius:6px;background:var(--sf-hover)}.sf-evidence-item small{display:block;color:var(--sf-ink3);font-size:11px}.sf-evidence-item strong{font-size:14px;font-variant-numeric:tabular-nums;overflow-wrap:anywhere}
/* 时间线（同步批次） */
.sf-timeline{display:grid;gap:0}.sf-timeline-row{display:grid;grid-template-columns:16px 1fr auto;gap:10px;padding:8px 0;border-bottom:1px solid var(--sf-line);align-items:start}.sf-timeline-row:last-child{border-bottom:0}.sf-timeline-dot{width:8px;height:8px;border-radius:50%;margin-top:5px;background:var(--sf-blue)}.sf-timeline-dot.is-green{background:var(--sf-green)}.sf-timeline-dot.is-rose{background:var(--sf-rose)}.sf-timeline-dot.is-amber{background:var(--sf-amber)}.sf-timeline-main{display:grid;gap:2px;min-width:0}.sf-timeline-main small{color:var(--sf-ink3);font-size:11px}
.sf-pager{display:flex;align-items:center;justify-content:flex-end;gap:10px;padding:8px 2px;color:var(--sf-ink2);font-size:12px}.sf-pager button{display:grid;place-items:center;width:26px;height:26px;border:1px solid var(--sf-line2);border-radius:6px;background:var(--sf-card);color:inherit;cursor:pointer}.sf-pager button:disabled{opacity:.4;cursor:default}
.sf-inline-form{display:grid;gap:10px;margin-bottom:12px;padding:12px;border:1px solid var(--sf-line2);border-radius:8px}
.sf-multi-search-select{display:grid;gap:7px;min-width:0;padding:8px;border:1px solid var(--sf-line2);border-radius:8px;background:var(--sf-card)}.sf-multi-search-input{display:flex;align-items:center;gap:6px}.sf-multi-search-input input{min-width:0;flex:1;min-height:30px;padding:4px 10px;border:1px solid var(--sf-line2);border-radius:6px;background:var(--sf-card);color:inherit;font:inherit;font-size:12px}.sf-multi-clear{display:grid;place-items:center;width:24px;height:24px;border:0;background:transparent;color:var(--sf-ink3);font-size:18px;line-height:1;cursor:pointer}.sf-multi-clear:disabled{cursor:default;opacity:.5}.sf-multi-summary{display:flex;align-items:center;gap:5px;min-width:0;flex-wrap:wrap;color:var(--sf-ink3);font-size:11px}.sf-multi-chip{max-width:150px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;padding:3px 7px;border:1px solid color-mix(in srgb,var(--sf-brand) 25%,var(--sf-line));border-radius:999px;background:color-mix(in srgb,var(--sf-brand) 7%,var(--sf-card));color:var(--sf-brand);font:inherit;font-size:11px;cursor:pointer}.sf-multi-chip:hover{background:color-mix(in srgb,var(--sf-brand) 14%,var(--sf-card))}.sf-multi-chip:disabled{cursor:default;opacity:.5}.sf-multi-more{color:var(--sf-ink3)}.sf-multi-options{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:4px;max-height:154px;overflow:auto;padding-right:2px}.sf-multi-option{display:flex;align-items:center;gap:7px;min-width:0;padding:6px 7px;border:1px solid transparent;border-radius:6px;background:transparent;color:inherit;text-align:left;font:inherit;font-size:12px;cursor:pointer}.sf-multi-option:hover{background:var(--sf-hover)}.sf-multi-option.is-selected{border-color:color-mix(in srgb,var(--sf-brand) 25%,var(--sf-line));background:color-mix(in srgb,var(--sf-brand) 7%,var(--sf-card))}.sf-multi-option>span:last-child{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.sf-multi-check{display:grid;flex:none;place-items:center;width:15px;height:15px;border:1px solid var(--sf-line2);border-radius:3px;color:var(--sf-on-brand);font-size:10px}.sf-multi-option.is-selected .sf-multi-check{border-color:var(--sf-brand);background:var(--sf-brand)}
.sf-task-options{display:grid;gap:8px}.sf-task-options label{display:flex;align-items:center;gap:8px;font-size:12px}.sf-task-options input{accent-color:var(--sf-brand)}
.sf-workbench{display:grid;gap:12px;padding:14px 16px;border:1px solid var(--sf-line);border-radius:10px;background:var(--sf-card)}.sf-workbench-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.sf-workbench-head h2{margin:0;font-size:14px}.sf-workbench-head p{margin:4px 0 0;color:var(--sf-ink3);font-size:12px}.sf-workbench-status{color:var(--sf-amber);font-size:12px}.sf-work-items{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.sf-work-item{display:grid;grid-template-columns:30px minmax(0,1fr) auto;align-items:center;gap:10px;min-width:0;padding:12px;border:1px solid var(--sf-line);border-radius:8px;background:var(--sf-hover);color:var(--sf-ink);text-align:left;cursor:pointer;transition:border-color .15s ease,background .15s ease,transform .15s ease}.sf-work-item:hover{border-color:var(--sf-brand);background:var(--sf-card);transform:translateY(-1px)}.sf-work-item:focus-visible{outline:2px solid var(--sf-brand);outline-offset:2px}.sf-work-item b{font-size:20px;font-variant-numeric:tabular-nums}.sf-work-icon{display:grid;place-items:center;width:30px;height:30px;border-radius:8px;background:color-mix(in srgb,var(--sf-brand) 12%,transparent);color:var(--sf-brand)}.sf-work-item.is-amber .sf-work-icon{background:color-mix(in srgb,var(--sf-amber) 16%,transparent);color:var(--sf-amber)}.sf-work-item.is-rose .sf-work-icon{background:color-mix(in srgb,var(--sf-rose) 14%,transparent);color:var(--sf-rose)}.sf-work-copy{display:grid;gap:3px;min-width:0}.sf-work-copy strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:12px}.sf-work-copy small{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--sf-ink3);font-size:11px}.sf-work-items.is-loading{min-height:56px}.sf-work-skeleton{height:56px;border-radius:8px;background:linear-gradient(90deg,var(--sf-hover),var(--sf-card),var(--sf-hover));background-size:200% 100%;animation:sf-shimmer 1.2s ease-in-out infinite}.sf-dc-summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.sf-dc-stat{display:grid;gap:4px;padding:12px 14px;border:1px solid var(--sf-line);border-radius:8px;background:var(--sf-card)}.sf-dc-stat span{color:var(--sf-ink2);font-size:12px}.sf-dc-stat strong{font-size:20px;font-variant-numeric:tabular-nums}.sf-dc-stat small{color:var(--sf-ink3);font-size:11px}.sf-banner .sf-btn{margin-left:auto}
/* 侧栏布局与 datasource 网页端保持一致，主内容独立滚动，避免横向页签占用首屏。 */
.sf-shell{grid-template-columns:220px minmax(0,1fr);grid-template-rows:auto 1fr}.sf-sidebar-brand{display:flex;grid-column:1;grid-row:1;align-items:center;gap:9px;padding:16px 14px;border-right:1px solid var(--sf-line);border-bottom:1px solid var(--sf-line);background:var(--sf-card)}.sf-sidebar-brand>div{display:grid;gap:1px;min-width:0}.sf-sidebar-brand strong{font-size:13px;white-space:nowrap}.sf-sidebar-brand small{color:var(--sf-ink3);font-size:10px}.sf-sidebar-brand-mark{display:grid;width:30px;height:30px;flex:none;place-items:center;border-radius:7px;background:var(--sf-brand);color:white}.sf-header{grid-column:2;grid-row:1}.sf-tabs{display:flex;grid-column:1;grid-row:2;flex-direction:column;align-items:stretch;gap:3px;width:auto;max-width:none;margin:0;padding:14px 10px;border:0;border-right:1px solid var(--sf-line);border-radius:0;background:var(--sf-card);overflow:auto}.sf-tabs button{width:100%;height:34px;padding:0 12px;text-align:left}.sf-tabs button[aria-current]{box-shadow:none;background:color-mix(in srgb,var(--sf-brand) 10%,transparent);color:var(--sf-brand)}.sf-content{grid-column:2;grid-row:2;min-width:0}.sf-main{display:contents}
@keyframes sf-shimmer{0%{background-position:200% 0}100%{background-position:-200% 0}}
@media(max-width:1100px){.sf-overview-grid{grid-template-columns:minmax(0,1fr)}}
@media(max-width:900px){.sf-header{padding:12px 16px}.sf-tabs{margin-left:16px;margin-right:16px;max-width:calc(100% - 32px)}.sf-content{padding:16px}.sf-kpis,.sf-stats{grid-template-columns:repeat(2,minmax(0,1fr))}.sf-two-col,.sf-work-items,.sf-dc-summary{grid-template-columns:1fr}.sf-form-row{grid-template-columns:110px minmax(0,1fr)}}
@media(max-width:900px){.sf-shell{grid-template-columns:1fr;grid-template-rows:auto auto auto 1fr}.sf-sidebar-brand{grid-column:1;grid-row:1}.sf-header{grid-column:1;grid-row:2}.sf-tabs{grid-column:1;grid-row:3;flex-direction:row;margin:0;padding:8px 16px;border-right:0;border-bottom:1px solid var(--sf-line);max-width:none;overflow-x:auto}.sf-tabs button{width:auto}.sf-content{grid-column:1;grid-row:4}}
@media(max-width:560px){.sf-multi-options{grid-template-columns:1fr}.sf-multi-chip{max-width:120px}}
.sf-search-select{position:relative}.sf-search-input-wrap{position:relative;display:flex;align-items:center}.sf-search-input-wrap input{padding-right:30px!important}.sf-search-clear{position:absolute;right:4px;display:grid;place-items:center;width:24px;height:24px;border:0;border-radius:4px;background:transparent;color:var(--sf-ink3);font:inherit;font-size:17px;line-height:1;cursor:pointer}.sf-search-clear:hover{background:var(--sf-hover);color:var(--sf-ink)}.sf-search-menu{position:absolute;z-index:30;top:calc(100% + 4px);right:0;left:0;display:grid;gap:2px;max-height:220px;overflow:auto;padding:4px;border:1px solid var(--sf-line2);border-radius:6px;background:var(--sf-card)}.sf-search-menu[hidden]{display:none}.sf-search-option{display:flex;align-items:center;justify-content:space-between;gap:8px;width:100%;padding:7px 8px;border:1px solid transparent;border-radius:4px;background:transparent;color:inherit;text-align:left;font:inherit;font-size:12px;cursor:pointer}.sf-search-option:hover,.sf-search-option.is-selected{border-color:color-mix(in srgb,var(--sf-brand) 24%,var(--sf-line));background:color-mix(in srgb,var(--sf-brand) 8%,var(--sf-card))}.sf-search-option:focus-visible,.sf-search-custom:focus-visible,.sf-search-clear:focus-visible{outline:2px solid var(--sf-brand);outline-offset:1px}.sf-search-empty{margin:0;padding:8px;color:var(--sf-ink3);font-size:12px;text-align:center}
`
