// 片段 4/7：样式系统。
// dsw token 映射前端四色语义：rose=error / amber=warn / emerald=success / sky+blue=business。
// pill/徽章底色用 color-mix 低透明度，浅色/深色皮肤均由宿主 token 适配。
const css = `
.sf-root{--sf-rose:var(--dsw-alias-state-error-primary);--sf-amber:var(--dsw-alias-state-warn-primary);--sf-green:var(--dsw-alias-state-success-primary);--sf-blue:var(--dsw-alias-state-business-primary);--sf-sky:var(--dsw-alias-state-business-primary);--sf-line:var(--dsw-alias-border-l1);--sf-line2:var(--dsw-alias-border-l2);--sf-bg:color-mix(in srgb,var(--dsw-alias-bg-layer-2) 45%,var(--dsw-alias-bg-base));--sf-card:var(--dsw-alias-bg-base);--sf-hover:var(--dsw-alias-bg-layer-2);--sf-ink:var(--dsw-alias-label-primary);--sf-ink2:var(--dsw-alias-label-secondary);--sf-ink3:var(--dsw-alias-label-tertiary);--sf-on-brand:var(--dsw-alias-label-primary-foreground)}
/* 品牌轴对齐 datasource 网页端浅绿工作台（agentspace 系）；暗色皮肤提亮保持对比度 */
.sf-root{--sf-brand:oklch(0.55 0.14 162)}[data-ds-dark-theme] .sf-root{--sf-brand:oklch(0.74 0.11 162)}
.sf-button{display:flex;width:36px;height:36px;align-items:center;justify-content:center;gap:8px;border:0;border-radius:6px;background:transparent;color:var(--sf-ink2);cursor:pointer}.sf-button:hover{background:var(--sf-hover);color:var(--sf-ink)}.sf-wide{width:100%;height:34px;justify-content:flex-start;padding:0 10px}.sf-wide span{font-size:13px}
.sf-overlay{position:fixed;inset:0;z-index:510;background:var(--sf-bg);color:var(--sf-ink);font-size:13px}.sf-shell{display:grid;grid-template-rows:auto auto 1fr;width:100%;height:100%;overflow:hidden}
.sf-header{display:flex;min-height:72px;align-items:flex-end;justify-content:space-between;gap:18px;padding:14px 28px 16px;border-bottom:1px solid var(--sf-line);flex-wrap:wrap}.sf-header-main{min-width:0}.sf-eyebrow{margin:0 0 2px;color:var(--sf-ink3);font-size:11px;font-weight:650;letter-spacing:.06em;text-transform:uppercase}.sf-header h1{margin:0;font-size:20px;line-height:1.35;font-weight:650}.sf-desc{margin:2px 0 0;color:var(--sf-ink2);font-size:12.5px}.sf-header-side{display:flex;align-items:flex-end;gap:10px;flex-wrap:wrap}.sf-filter{display:grid;gap:4px}.sf-filter>span{color:var(--sf-ink3);font-size:11px}.sf-filter select{min-width:130px;height:30px;padding:4px 10px;border:1px solid var(--sf-line2);border-radius:6px;background:var(--sf-card);color:inherit;font:inherit;font-size:12.5px;cursor:pointer}.sf-header-buttons{display:flex;gap:6px}
.sf-icon-button{display:grid;width:36px;height:36px;place-items:center;border:1px solid var(--sf-line);border-radius:6px;background:var(--sf-card);color:inherit;cursor:pointer}.sf-icon-button:hover{background:var(--sf-hover)}

.sf-tabs{display:inline-flex;gap:2px;margin:12px 28px 0;padding:3px;border:1px solid var(--sf-line);border-radius:8px;background:color-mix(in srgb,var(--dsw-alias-bg-layer-2) 62%,transparent);width:fit-content;max-width:calc(100% - 56px);overflow-x:auto}.sf-tabs button{height:30px;padding:0 14px;border:0;border-radius:6px;background:transparent;color:var(--sf-ink2);font:inherit;font-size:12.5px;white-space:nowrap;cursor:pointer}.sf-tabs button[aria-current]{background:var(--sf-card);color:var(--sf-ink);font-weight:650;box-shadow:0 1px 2px color-mix(in srgb,var(--sf-ink) 8%,transparent)}
.sf-content{overflow:auto;padding:16px 28px 44px}.sf-content.sf-refreshing{opacity:.62;transition:opacity .2s}
.sf-view{display:grid;gap:16px;max-width:1680px;margin:0 auto}
/* 卡片：去阴影直角 + 标题分隔线（对齐前端 Card 约定） */
.sf-card{min-width:0;border:1px solid var(--sf-line);border-radius:8px;background:var(--sf-card)}.sf-card-head{display:flex;align-items:center;gap:10px;padding:12px 16px;border-bottom:1px solid var(--sf-line)}.sf-card-head h2{margin:0;font-size:13px;font-weight:650}.sf-card-unit{color:var(--sf-ink3);font-size:11px}.sf-card-actions{display:flex;align-items:center;gap:8px;margin-left:auto}.sf-card-body{padding:12px 16px}.sf-card-body.is-flush{padding:0}
/* KPI 卡 */
.sf-kpis{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:12px}.sf-kpi{display:grid;gap:6px;align-content:start;padding:14px 16px;border:1px solid var(--sf-line);border-radius:8px;background:var(--sf-card)}.sf-kpi.is-clickable{cursor:pointer;transition:border-color .15s}.sf-kpi.is-clickable:hover{border-color:var(--sf-brand)}.sf-kpi-top{display:flex;align-items:center;justify-content:space-between}.sf-kpi-label{color:var(--sf-ink2);font-size:12px}.sf-kpi-icon{display:grid;width:32px;height:32px;place-items:center;border:1px solid var(--sf-line);border-radius:6px;background:color-mix(in srgb,var(--sf-hover) 55%,transparent);color:color-mix(in srgb,var(--sf-ink) 70%,var(--sf-ink2))}.sf-kpi-value{font-size:20px;line-height:1.2;font-weight:650;font-variant-numeric:tabular-nums;overflow-wrap:anywhere}.sf-kpi.is-neg .sf-kpi-value{color:color-mix(in srgb,var(--sf-rose) 70%,var(--sf-ink))}.sf-kpi-hint{color:var(--sf-ink3);font-size:11px}.sf-hint-up{color:color-mix(in srgb,var(--sf-green) 75%,var(--sf-ink))}.sf-hint-down{color:color-mix(in srgb,var(--sf-rose) 75%,var(--sf-ink))}.sf-hint-warn{color:color-mix(in srgb,var(--sf-amber) 75%,var(--sf-ink))}
/* 统计卡（预警中心）：可点击筛选，激活 ring */
.sf-stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.sf-stat{display:grid;gap:2px;justify-items:start;padding:12px 14px;border:1px solid var(--sf-line);border-radius:8px;background:var(--sf-card);color:inherit;font:inherit;text-align:left}.sf-stat.is-clickable{cursor:pointer}.sf-stat.is-active{box-shadow:0 0 0 2px var(--sf-brand)}.sf-stat strong{font-size:20px;font-variant-numeric:tabular-nums}.sf-stat span{color:var(--sf-ink2);font-size:12px}.sf-stat-rose strong{color:color-mix(in srgb,var(--sf-rose) 75%,var(--sf-ink))}.sf-stat-amber strong{color:color-mix(in srgb,var(--sf-amber) 75%,var(--sf-ink))}.sf-stat-sky strong{color:color-mix(in srgb,var(--sf-sky) 75%,var(--sf-ink))}.sf-stat-green strong{color:color-mix(in srgb,var(--sf-green) 75%,var(--sf-ink))}
/* 徽章与 pill */
.sf-badge{display:inline-flex;align-items:center;padding:1px 8px;border-radius:999px;border:1px solid var(--sf-line);font-size:11px;color:var(--sf-ink2)}.sf-badge-rose{color:color-mix(in srgb,var(--sf-rose) 75%,var(--sf-ink));border-color:color-mix(in srgb,var(--sf-rose) 35%,transparent)}.sf-badge-amber{color:color-mix(in srgb,var(--sf-amber) 75%,var(--sf-ink));border-color:color-mix(in srgb,var(--sf-amber) 35%,transparent)}.sf-badge-green{color:color-mix(in srgb,var(--sf-green) 75%,var(--sf-ink));border-color:color-mix(in srgb,var(--sf-green) 35%,transparent)}.sf-badge-blue,.sf-badge-sky{color:color-mix(in srgb,var(--sf-blue) 75%,var(--sf-ink));border-color:color-mix(in srgb,var(--sf-blue) 35%,transparent)}
.sf-pill{display:inline-flex;align-items:center;padding:2px 9px;border-radius:999px;font-size:11px;white-space:nowrap}.sf-pill-muted{background:var(--sf-hover);color:var(--sf-ink2)}.sf-pill-rose{background:color-mix(in srgb,var(--sf-rose) 14%,transparent);color:color-mix(in srgb,var(--sf-rose) 78%,var(--sf-ink))}.sf-pill-amber{background:color-mix(in srgb,var(--sf-amber) 16%,transparent);color:color-mix(in srgb,var(--sf-amber) 78%,var(--sf-ink))}.sf-pill-green{background:color-mix(in srgb,var(--sf-green) 14%,transparent);color:color-mix(in srgb,var(--sf-green) 78%,var(--sf-ink))}.sf-pill-blue{background:color-mix(in srgb,var(--sf-blue) 14%,transparent);color:color-mix(in srgb,var(--sf-blue) 78%,var(--sf-ink))}
/* 表格：无斑马纹，行 border-b + hover，数字右对齐，可选 sticky 首列 */
.sf-table-scroll{max-width:100%;overflow-x:auto}.sf-table{width:100%;border-collapse:collapse;font-size:12px;font-variant-numeric:tabular-nums}.sf-table th,.sf-table td{padding:8px 10px;border-bottom:1px solid var(--sf-line);text-align:right;white-space:nowrap}.sf-table th:first-child,.sf-table td:first-child{text-align:left}.sf-table th{color:var(--sf-ink3);font-weight:500;font-size:11px}.sf-table tbody tr{background:transparent}.sf-table tbody tr:hover{background:var(--sf-hover)}.sf-table tbody tr:last-child td{border-bottom:0}.sf-table tr.is-clickable{cursor:pointer}.sf-num{font-variant-numeric:tabular-nums}.sf-sticky-col{position:sticky;left:0;background:var(--sf-card);z-index:1;text-align:left}.sf-table tbody tr:hover .sf-sticky-col{background:var(--sf-hover)}
/* 热力格（执行率） */
.sf-heat{display:inline-flex;align-items:center;padding:2px 8px;border-radius:6px;font-weight:650}.sf-heat-over{background:color-mix(in srgb,var(--sf-rose) 16%,transparent);color:color-mix(in srgb,var(--sf-rose) 80%,var(--sf-ink))}.sf-heat-healthy{background:color-mix(in srgb,var(--sf-green) 14%,transparent);color:color-mix(in srgb,var(--sf-green) 80%,var(--sf-ink))}.sf-heat-slow{background:color-mix(in srgb,var(--sf-amber) 16%,transparent);color:color-mix(in srgb,var(--sf-amber) 80%,var(--sf-ink))}.sf-heat-early{background:var(--sf-hover);color:var(--sf-ink2)}
.sf-neg{color:color-mix(in srgb,var(--sf-rose) 70%,var(--sf-ink));font-weight:650}.sf-pos{color:color-mix(in srgb,var(--sf-green) 70%,var(--sf-ink))}
/* 进度条 */
.sf-progress{height:6px;min-width:80px;border-radius:4px;background:var(--sf-hover);overflow:hidden}.sf-progress-fill{height:100%;border-radius:4px;background:var(--sf-brand)}.sf-progress-fill.is-green{background:var(--sf-green)}.sf-progress-fill.is-amber{background:var(--sf-amber)}.sf-progress-fill.is-rose{background:var(--sf-rose)}
/* pill 页签 */
.sf-pilltabs{display:inline-flex;flex-wrap:wrap;gap:2px;padding:2px;border:1px solid var(--sf-line);border-radius:8px;background:var(--sf-card)}.sf-pilltabs button{min-width:72px;height:28px;padding:0 12px;border:0;border-radius:6px;background:transparent;color:var(--sf-ink2);font:inherit;font-size:12px;cursor:pointer}.sf-pilltabs button.is-active{background:var(--sf-ink);color:var(--sf-bg);font-weight:650}
/* 表单 */
.sf-form{display:grid;gap:12px;max-width:640px}.sf-form-row{display:grid;grid-template-columns:140px minmax(0,1fr);align-items:center;gap:12px}.sf-form-row>span{color:var(--sf-ink2);font-size:12px}.sf-form-row input,.sf-form-row select,.sf-form-row textarea{min-height:30px;padding:4px 10px;border:1px solid var(--sf-line2);border-radius:6px;background:var(--sf-card);color:inherit;font:inherit;font-size:13px}.sf-form-row textarea{min-height:56px;resize:vertical}.sf-form-actions{display:flex;align-items:center;gap:12px}
.sf-btn{display:inline-flex;align-items:center;gap:6px;height:30px;padding:0 14px;border-radius:6px;border:1px solid transparent;font:inherit;font-size:12.5px;cursor:pointer}.sf-btn:disabled{opacity:.5;cursor:default}.sf-btn-primary{border:0;background:var(--sf-brand);color:var(--sf-on-brand);font-weight:600}.sf-btn-ghost{border-color:var(--sf-line2);background:var(--sf-card);color:inherit}.sf-btn-ghost:hover{background:var(--sf-hover)}.sf-link{border:0;background:transparent;color:var(--sf-brand);font:inherit;font-size:12px;cursor:pointer;text-decoration:underline;padding:0}
.sf-switch{position:relative;display:inline-block;width:34px;height:19px;border:0;border-radius:999px;background:var(--sf-hover);cursor:pointer;transition:background .15s}.sf-switch.is-on{background:var(--sf-green)}.sf-switch-knob{position:absolute;top:2px;left:2px;width:15px;height:15px;border-radius:50%;background:var(--sf-card);transition:left .15s}.sf-switch.is-on .sf-switch-knob{left:17px}
/* Dialog */
.sf-dialog-mask{position:fixed;inset:0;z-index:20;display:grid;place-items:center;background:color-mix(in srgb,var(--sf-bg) 55%,transparent);backdrop-filter:blur(2px)}.sf-dialog{display:grid;grid-template-rows:auto 1fr auto;max-height:82vh;max-width:92vw;border:1px solid var(--sf-line);border-radius:10px;background:var(--sf-card);box-shadow:0 18px 48px color-mix(in srgb,var(--sf-ink) 18%,transparent);outline:none}.sf-dialog-sm{width:420px}.sf-dialog-md{width:640px}.sf-dialog-lg{width:920px}.sf-dialog-head{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:14px 18px;border-bottom:1px solid var(--sf-line)}.sf-dialog-head h3{margin:0;font-size:14px}.sf-dialog-body{padding:16px 18px;overflow:auto}.sf-dialog-foot{display:flex;justify-content:flex-end;gap:10px;padding:12px 18px;border-top:1px solid var(--sf-line)}
/* 图表 */
.sf-chart-wrap{display:grid;gap:10px}.sf-chart-legend{display:flex;justify-content:flex-end;gap:14px;color:var(--sf-ink2);font-size:11px}.sf-chart-legend span{display:inline-flex;align-items:center;gap:5px}.sf-legend{display:inline-block;width:12px;height:8px;border-radius:2px}.sf-legend-a{background:var(--sf-brand)}.sf-legend-b{background:color-mix(in srgb,var(--sf-brand) 45%,transparent)}.sf-legend-c{background:color-mix(in srgb,var(--sf-green) 70%,transparent)}.sf-legend-rose{background:var(--sf-rose)}.sf-legend-amber{background:var(--sf-amber)}.sf-legend-green{background:var(--sf-green)}.sf-legend-blue{background:var(--sf-blue)}
.sf-chart{width:100%;height:auto;min-height:170px;overflow:visible}.sf-grid-line{stroke:var(--sf-line);stroke-width:1}.sf-bar-a{fill:var(--sf-brand)}.sf-bar-b{fill:color-mix(in srgb,var(--sf-brand) 45%,transparent)}.sf-bar-c{fill:color-mix(in srgb,var(--sf-green) 70%,transparent)}.sf-bar-group.is-clickable{cursor:pointer}.sf-bar-group.is-clickable:hover .sf-bar{opacity:.8}.sf-chart-label{fill:var(--sf-ink3);font-size:11px}
/* 瀑布 / 占比 / 净额 */
.sf-waterfall{display:flex;align-items:flex-end;gap:18px;min-height:170px;padding:6px 2px;overflow-x:auto}.sf-waterfall-item{display:grid;gap:4px;justify-items:center;min-width:64px}.sf-waterfall-bar-area{display:flex;align-items:flex-end;height:110px;width:34px;border-bottom:1px solid var(--sf-line)}.sf-waterfall-bar{width:100%;border-radius:4px 4px 0 0;background:var(--sf-brand)}.sf-waterfall-bar.is-rose{background:var(--sf-rose)}.sf-waterfall-bar.is-green{background:var(--sf-green)}.sf-waterfall-bar.is-amber{background:var(--sf-amber)}.sf-waterfall-label{color:var(--sf-ink2);font-size:11px}.sf-waterfall-value{font-size:11px;font-variant-numeric:tabular-nums}
.sf-share{display:grid;gap:10px}.sf-share-track{display:flex;height:14px;border-radius:6px;overflow:hidden}.sf-share-seg{height:100%}.sf-share-seg.is-a{background:var(--sf-brand)}.sf-share-seg.is-b{background:color-mix(in srgb,var(--sf-brand) 45%,transparent)}.sf-share-seg.is-c{background:color-mix(in srgb,var(--sf-green) 70%,transparent)}.sf-share-seg.is-d{background:color-mix(in srgb,var(--sf-amber) 60%,transparent)}.sf-share-legend{display:flex;flex-wrap:wrap;gap:12px;color:var(--sf-ink2);font-size:11px}.sf-share-legend span{display:inline-flex;align-items:center;gap:5px}
.sf-netbars{display:grid;gap:6px}.sf-netbar-row{display:grid;grid-template-columns:64px 1fr 76px;align-items:center;gap:10px}.sf-netbar-label{color:var(--sf-ink2);font-size:11px}.sf-netbar-track{display:flex;height:12px}.sf-netbar-half{display:flex;flex:1}.sf-netbar-half.is-left{justify-content:flex-end}.sf-netbar-zero{width:1px;background:var(--sf-line2)}.sf-netbar-bar{height:100%;border-radius:3px}.sf-netbar-bar.is-green{background:var(--sf-green)}.sf-netbar-bar.is-rose{background:var(--sf-rose)}.sf-netbar-value{text-align:right;font-size:11px;font-variant-numeric:tabular-nums}
/* 口径条（网页端 bg-card 边框说明条）与总览非对称双栏（趋势 1.2fr / 主体 0.8fr） */
.sf-scopebar{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap;padding:8px 12px;border:1px solid var(--sf-line);border-radius:8px;background:var(--sf-card);color:var(--sf-ink2);font-size:12px}.sf-overview-grid{display:grid;gap:16px;grid-template-columns:minmax(0,1.2fr) minmax(320px,.8fr)}
/* 布局辅助 */
.sf-two-col{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.sf-stack{display:grid;gap:16px;min-width:0}.sf-row{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.sf-row-between{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap}.sf-filters{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,max-content));gap:10px;align-items:center}
/* 提示与状态 */
.sf-notice{margin:0;color:var(--sf-ink2);font-size:12px}.sf-notice-rose{color:color-mix(in srgb,var(--sf-rose) 75%,var(--sf-ink))}.sf-notice-green{color:color-mix(in srgb,var(--sf-green) 75%,var(--sf-ink))}.sf-banner{display:flex;align-items:center;gap:10px;padding:10px 14px;border-radius:8px;font-size:12.5px}.sf-banner-amber{background:color-mix(in srgb,var(--sf-amber) 12%,transparent);color:color-mix(in srgb,var(--sf-amber) 80%,var(--sf-ink))}.sf-banner-green{background:color-mix(in srgb,var(--sf-green) 12%,transparent);color:color-mix(in srgb,var(--sf-green) 80%,var(--sf-ink))}.sf-banner .sf-btn{margin-left:auto}
.sf-note{margin:0;color:var(--sf-ink3);font-size:12px;line-height:1.55}.sf-empty,.sf-loading,.sf-fatal{display:grid;min-height:110px;place-items:center;align-content:center;gap:8px;color:var(--sf-ink2);font-size:13px;text-align:center}
/* 证据快照数字网格 */
.sf-evidence{display:grid;grid-template-columns:repeat(auto-fill,minmax(150px,1fr));gap:8px}.sf-evidence-item{padding:8px 10px;border:1px solid var(--sf-line);border-radius:6px;background:var(--sf-hover)}.sf-evidence-item small{display:block;color:var(--sf-ink3);font-size:11px}.sf-evidence-item strong{font-size:14px;font-variant-numeric:tabular-nums;overflow-wrap:anywhere}
/* 时间线（同步批次） */
.sf-timeline{display:grid;gap:0}.sf-timeline-row{display:grid;grid-template-columns:16px 1fr auto;gap:10px;padding:8px 0;border-bottom:1px solid var(--sf-line);align-items:start}.sf-timeline-row:last-child{border-bottom:0}.sf-timeline-dot{width:8px;height:8px;border-radius:50%;margin-top:5px;background:var(--sf-blue)}.sf-timeline-dot.is-green{background:var(--sf-green)}.sf-timeline-dot.is-rose{background:var(--sf-rose)}.sf-timeline-dot.is-amber{background:var(--sf-amber)}.sf-timeline-main{display:grid;gap:2px;min-width:0}.sf-timeline-main small{color:var(--sf-ink3);font-size:11px}
.sf-pager{display:flex;align-items:center;justify-content:flex-end;gap:10px;padding:8px 2px;color:var(--sf-ink2);font-size:12px}.sf-pager button{display:grid;place-items:center;width:26px;height:26px;border:1px solid var(--sf-line2);border-radius:6px;background:var(--sf-card);color:inherit;cursor:pointer}.sf-pager button:disabled{opacity:.4;cursor:default}
.sf-inline-form{display:grid;gap:10px;margin-bottom:12px;padding:12px;border:1px solid var(--sf-line2);border-radius:8px}
@media(max-width:1100px){.sf-overview-grid{grid-template-columns:minmax(0,1fr)}}
@media(max-width:900px){.sf-header{padding:12px 16px}.sf-tabs{margin-left:16px;margin-right:16px;max-width:calc(100% - 32px)}.sf-content{padding:16px}.sf-kpis,.sf-stats{grid-template-columns:repeat(2,minmax(0,1fr))}.sf-two-col{grid-template-columns:1fr}.sf-form-row{grid-template-columns:110px minmax(0,1fr)}}
`
