import { defineConfig } from 'tsdown'

const PACKAGE_NAME = '@dofe/dsh-sensteed-product'

export default defineConfig([
  {
    name: PACKAGE_NAME,
    entry: {
      index: 'src/index.ts',
      'package-version': 'src/package-version.ts',
      'dofe-models': 'src/dofe-models.ts',
      'dofe-plugins': 'src/dofe-plugins.ts',
      'dofe-auth-contract': 'src/dofe-auth-contract.ts',
      'dofe-auth-oidc': 'src/dofe-auth-oidc.ts',
      'finance-mcp': 'src/finance-mcp.ts',
      'knowledge-routing': 'src/knowledge-routing.ts',
      'yootun-audit-contract': 'src/yootun-audit-contract.ts',
      'yootun-audit-store': 'src/yootun-audit-store.ts',
      'yootun-audit-models-client': 'src/yootun-audit-models-client.ts',
      'yootun-audit-service': 'src/yootun-audit-service.ts',
      'yootun-audit-route': 'src/yootun-audit-route.ts',
      'yootun-route-security': 'src/yootun-route-security.ts',
      'yootun-recruiter-route': 'src/yootun-recruiter-route.ts',
      'yootun-sales-route': 'src/yootun-sales-route.ts',
      'yootun-finops-route': 'src/yootun-finops-route.ts',
      'yootun-supply-watch-route': 'src/yootun-supply-watch-route.ts',
      'yootun-dashboard-activity': 'src/yootun-dashboard-activity.ts',
      'yootun-recruiter-integrations': 'src/yootun-recruiter-integrations.ts',
      'yootun-recruiter-tools': 'src/yootun-recruiter-tools.ts',
      'dofe-managed': 'src/dofe-managed.ts',
      'dofe-opencli': 'src/dofe-opencli.ts',
      'personal-knowledge-files': 'src/personal-knowledge-files.ts',
      'dofe-auth-route': 'src/dofe-auth-route.ts',
      'dofe-auth-audit': 'src/dofe-auth-audit.ts',
      'dofe-access-route': 'src/dofe-access-route.ts',
      'dofe-auth-service': 'src/dofe-auth-service.ts',
      routes: 'src/routes.ts',
    },
    outDir: 'lib',
    format: 'esm',
    platform: 'node',
    target: 'es2024',
    fixedExtension: false,
    dts: false,
    clean: false,
    sourcemap: true,
  },
])
